# Permalinks
permalink:      pretty

# Setup
title:          Blue
subtitle:       Minimalist Jekyll theme (based on Bulma)
baseurl:        
url:            "https://jsalvador.me"
color:          primary

author:
  name:         Juanjo Salvador
  url:          http://jsalvador.me
  email:        juanjosalvador@netc.eu             # Place your email here
  github:       JuanjoSalvador                     # Place your GitHub username here
  twitter:      Linuxneitor                        # Place your twitter username here
  mastodon:     https://mastodon.social/@jsalvador # Place your profile URL here

# Assets
sass:
  #sass_dir:     _sass
  style:        compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Custom vars
version:        3.8.5
paginate:       1
paginate_path: "/page:num/"

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
