# Permalinks
#permalink:      pretty

# Setup
title:          Blue
subtitle:       Minimalist Jekyll theme (based on Bulma)
paginate:       5
baseurl:        
url:            "https://jsalvador.me"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown
highlighter:    rouge

# About
author:
  name:         Juanjo Salvador
  url:          http://jsalvador.me
  email:        juanjosalvador@netc.eu

# Custom vars
version:        3.8.5
paginate:       5

plugins: [jekyll-paginate]
