# Permalinks
permalink:      pretty

# Setup
title:          Blue
description:    Minimalist Jekyll theme based on Bulma.
baseurl:        
url:            "https://jsalvador.me"

color:          link

author:
  name:         Juanjo Salvador
  url:          http://jsalvador.me
  email:                                           # Place your email here
  github:       JuanjoSalvador                     # Place your GitHub username here
  twitter:      Linuxneitor                        # Place your twitter username here
  mastodon:     https://mastodon.social/@jsalvador # Place your profile URL here

twitter:
  username: Linuxneitor
  card: summary
locale: es_ES

# Assets
sass:
  style:        compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Custom vars
version:        4.3.3
paginate:       5                                  # Default pagination is 5 post per page
paginate_path: "/page:num/"

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
