# Permalinks
#permalink:      pretty

# Setup
title:          Blue
subtitle:       Minimalist Jekyll theme (based on Bulma)
baseurl:        
url:            "https://jsalvador.me"
color:          primary

author:
  name:         Juanjo Salvador
  url:          http://jsalvador.me
  email:        juanjosalvador@netc.eu

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Custom vars
version:        3.8.5
paginate:       1
paginate_path: "/page:num/"

plugins: [jekyll-paginate]
